# Site settings
title: André Naz - Personal Web Page
name: André Naz
description: "PhD in Computer Science - Software Engineer"
baseurl: "" # the subpath of the site
url: "http://nazandre.github.io"

# Google analytics
# Configuration taken from https://desiredpersona.com/google-analytics-jekyll/
google_analytics: UA-94101924-1

# Social networks and contacts:
github_username:  nazandre
linkedin_username: andre-naz
facebook_username: andre.naz.37
#professional_url: http://www.femto-st.fr/fr/Annuaire//u-%7Bf25149cb-f430-c4f9-c5f0-59da9ebe3b49%7D-Naz-Andre/L2ZyL0FubnVhaXJlLz9kaWR0aWQ9JmZuYW1lPSZsbmFtZT1HTElTRVMmc3RhdHVzPTAmZnU9RW52b3llcg%3D%3D/
#professional_url: https://www.femto-st.fr/en/femto-people/anaz2
researchgate_username: Andre_Naz
email: andre.naz01@gmail.com

# CV
cv_url: "/files/andre-naz-cv.pdf"

#blog_url: "/blog"
#vk_username: your_vk_username_goes_here
#twitter_username: your_twitter_username_goes_here
#google_plus_username: your_google_plus_username_goes_here
#vine_username:  your_vine_username_goes_here
#instagram_username:  your_instagram_username_goes_here
#flickr_username: your_flickr_username_goes_here
#steam_username: your_steam_username_goes_here
#soundcloud_username:  your_soundcloud_username_goes_here
#stack_of_username: your_stack_overflow_account_id_number_goes_here
#reddit_username: your_reddit_username_goes_here
#medium_username:  your_medium_username_goes_here
#tumblr_username: your_tumblr_username_goes_here
#weibo_username: your_weibo_username_goes_here
#lastfm_username: your_lastfm_username_goes_here
#public_key_url: "https://raw.pastebin.com/LINK-TO-PUBLIC-KEY"

# Avatar:
avatar: yes
avatar_img_path: "imgs/me.jpg"
# You can link to your GitHub image. That way it will get updated
# automatically whenever you change your GitHub profile picture
#avatar_img_path: "https://avatars2.githubusercontent.com/u/17301305"

# Background image:
front_img: yes
front_img_path: "imgs/background1.jpg"
#front_img_path: "https://external.url/image.jpg"

# Github icons:
favicon_img: yes
favicon_img_path: "imgs/favicon.ico"
#favicon_img_path: "https://external.url/favicon.ico"

# Build settings
markdown: kramdown
permalink: pretty
